# Generated by Django 2.2.1 on 2019-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='earlier_login',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fblink',
            field=models.URLField(max_length=120, null=True),
        ),
    ]
