# Generated by Django 2.2.1 on 2019-06-02 19:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190602_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='por',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
