# Generated by Django 2.2.1 on 2019-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
