# Generated by Django 2.2.1 on 2019-06-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190603_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_img',
            new_name='image',
        ),
    ]
