# Generated by Django 2.2.1 on 2019-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privilege', '0001_initial'),
        ('acads', '0001_initial'),
        ('tags', '0001_initial'),
        ('users', '0009_auto_20190603_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acads',
            field=models.ManyToManyField(to='acads.AcadsModel'),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ManyToManyField(through='privilege.privileges', to='tags.TagModel'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='tags.TagModel'),
        ),
    ]
