# Generated by Django 2.2.1 on 2019-07-03 22:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('acads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_long', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('venue', models.CharField(max_length=20)),
                ('venue_id', models.IntegerField()),
                ('acad_state', models.BooleanField(default=False)),
                ('hash_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('acads', models.ManyToManyField(to='acads.AcadsModel')),
                ('tags', models.ManyToManyField(to='tags.TagModel')),
            ],
        ),
    ]
