# Generated by Django 2.2.1 on 2019-07-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='venue_id',
            field=models.IntegerField(null=True),
        ),
    ]
