# Generated by Django 2.2.3 on 2019-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190703_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='acads',
            field=models.ManyToManyField(related_name='events', to='acads.AcadsModel'),
        ),
    ]
