# Generated by Django 2.2.2 on 2019-06-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('events', '0004_auto_20190626_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='tags',
            field=models.ManyToManyField(to='tags.TagModel'),
        ),
    ]
