# Generated by Django 2.2.2 on 2019-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0001_initial'),
        ('events', '0005_eventmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='acad_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='acads',
            field=models.ManyToManyField(to='acads.AcadsModel'),
        ),
    ]
