<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-06-29 22:08
=======
# Generated by Django 2.2.2 on 2019-06-29 18:06
>>>>>>> To be squahsed
=======
# Generated by Django 2.2.2 on 2019-06-29 22:38
>>>>>>> corrected APIs

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcadsModel',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
    ]
