# Generated by Django 2.2.3 on 2019-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadsmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
