<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-06-29 22:08
=======
# Generated by Django 2.2.2 on 2019-06-29 22:38
>>>>>>> corrected APIs

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('privilege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privileges',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
