# Generated by Django 2.2.2 on 2019-06-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
